// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DashboardUIClient is the client API for DashboardUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardUIClient interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (DashboardUI_ListDocumentSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type dashboardUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardUIClient(cc grpc.ClientConnInterface) DashboardUIClient {
	return &dashboardUIClient{cc}
}

func (c *dashboardUIClient) ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (DashboardUI_ListDocumentSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DashboardUI_ServiceDesc.Streams[0], "/v1.DashboardUI/ListDocumentSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &dashboardUIListDocumentSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DashboardUI_ListDocumentSpecsClient interface {
	Recv() (*ListDocumentSpecsResponse, error)
	grpc.ClientStream
}

type dashboardUIListDocumentSpecsClient struct {
	grpc.ClientStream
}

func (x *dashboardUIListDocumentSpecsClient) Recv() (*ListDocumentSpecsResponse, error) {
	m := new(ListDocumentSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dashboardUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DashboardUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardUIServer is the server API for DashboardUI service.
// All implementations must embed UnimplementedDashboardUIServer
// for forward compatibility
type DashboardUIServer interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(*ListDocumentSpecsRequest, DashboardUI_ListDocumentSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDashboardUIServer()
}

// UnimplementedDashboardUIServer must be embedded to have forward compatible implementations.
type UnimplementedDashboardUIServer struct {
}

func (UnimplementedDashboardUIServer) ListDocumentSpecs(*ListDocumentSpecsRequest, DashboardUI_ListDocumentSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDocumentSpecs not implemented")
}
func (UnimplementedDashboardUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDashboardUIServer) mustEmbedUnimplementedDashboardUIServer() {}

// UnsafeDashboardUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardUIServer will
// result in compilation errors.
type UnsafeDashboardUIServer interface {
	mustEmbedUnimplementedDashboardUIServer()
}

func RegisterDashboardUIServer(s grpc.ServiceRegistrar, srv DashboardUIServer) {
	s.RegisterService(&DashboardUI_ServiceDesc, srv)
}

func _DashboardUI_ListDocumentSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardUIServer).ListDocumentSpecs(m, &dashboardUIListDocumentSpecsServer{stream})
}

type DashboardUI_ListDocumentSpecsServer interface {
	Send(*ListDocumentSpecsResponse) error
	grpc.ServerStream
}

type dashboardUIListDocumentSpecsServer struct {
	grpc.ServerStream
}

func (x *dashboardUIListDocumentSpecsServer) Send(m *ListDocumentSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DashboardUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DashboardUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardUI_ServiceDesc is the grpc.ServiceDesc for DashboardUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DashboardUI",
	HandlerType: (*DashboardUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DashboardUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDocumentSpecs",
			Handler:       _DashboardUI_ListDocumentSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dashboard-ui.proto",
}
